require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Max: 120
  CountComments: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false